var pixel=pixel||{pixelConfig:null,segmentConfig:null,extraParams:null,cookieDomain:null,domainList:[],clickTrackers:null,initialize:null,finalize:null,paramArray:[],segParams:[],pageLoadStatusFlag:false,checkReadyStateOnIntervals:null,checkReadyStateTimeout:null,pixelFireStatus:false,ON_SCROLL_INTERVAL_IN_MINUTES:1,ON_SCROLL_POPUP_LIMIT_PER_DAY:5,ON_IDLE_TIME_INTERVAL_IN_MINUTES:1,ON_IDLE_TIME_POPUP_LIMIT_PER_DAY:5,EXIT_INTENT_INTERVAL_IN_MINUTES:1,EXIT_INTENT_POPUP_LIMIT_PER_DAY:5,ONSITE_MESSAGE_COOKIE_NAME:"onSiteMsgCookie",IDLE_TIME_IN_MINUTES:2,onSiteNotificationConfig:null,onsiteCurrentUrlNotificationConfig:{},currentOnsitePopup:null,CHATBOT_USER_COOKIE_KEY:"chatbot_user",CHATBOT_USER_COOKIE_EXPIRY:360,CHATBOT_USER_COOKIE_VALUE:null,loadContentForOnSiteMsg2:function(){try{var ENGAGEMENT_ON_SCROLL_PERCENTAGE=null;var URL_FOR_ONSITE_POP_UP=window.location.href;var currentUrlConfigOnScroll=null;var currentUrlConfigOnIdleTime=null;var currentUrlConfigExitIntent=null;var OnsitePopupTypes=["modalOnScroll","modalOnIdleTime","modalExitIntent",];for(var i=0;i<OnsitePopupTypes.length;i++){var currOnsiteElement=document.getElementById(OnsitePopupTypes[i]);if(currOnsiteElement==null)continue;currOnsiteElement.remove();}
if(pixel.onSiteNotificationConfig){var obj=pixel.onSiteNotificationConfig;for(var urlKey in obj){var OnScroll=null;var OnIdleTime=null;var ExitIntent=null;var currentOnsiteUrlNotificationConfig=pixel.onSiteNotificationConfig[urlKey];if(!currentOnsiteUrlNotificationConfig)continue;try{OnScroll=currentOnsiteUrlNotificationConfig["ON_SCROLL"][0];}catch(error){}
try{OnIdleTime=currentOnsiteUrlNotificationConfig["ON_IDLE_TIME"][0];}catch(error){}
try{ExitIntent=currentOnsiteUrlNotificationConfig["EXIT_INTENT"][0];}catch(error){}
if(OnScroll){var isSubString=OnScroll.urlIsSubstring;if(isSubString=="1"){if(!URL_FOR_ONSITE_POP_UP.includes(OnScroll.url)){OnScroll=null;}}else{if(URL_FOR_ONSITE_POP_UP!=OnScroll.url){OnScroll=null;}}}
if(OnIdleTime){var isSubString=OnIdleTime.urlIsSubstring;if(isSubString=="1"){if(!URL_FOR_ONSITE_POP_UP.includes(OnIdleTime.url)){OnIdleTime=null;}}else{if(URL_FOR_ONSITE_POP_UP!=OnIdleTime.url){OnIdleTime=null;}}}
if(ExitIntent){var isSubString=ExitIntent.urlIsSubstring;if(isSubString=="1"){if(!URL_FOR_ONSITE_POP_UP.includes(ExitIntent.url)){ExitIntent=null;}}else{if(URL_FOR_ONSITE_POP_UP!=ExitIntent.url){ExitIntent=null;}}}
if(OnIdleTime!=null&&currentUrlConfigOnIdleTime==null){currentUrlConfigOnIdleTime=OnIdleTime;}
if(OnScroll!=null&&currentUrlConfigOnScroll==null){currentUrlConfigOnScroll=OnScroll;}
if(ExitIntent!=null&&currentUrlConfigExitIntent==null){currentUrlConfigExitIntent=ExitIntent;}
if(currentUrlConfigOnIdleTime&&currentUrlConfigOnScroll&&currentUrlConfigExitIntent)
break;}}
if(currentUrlConfigOnScroll){var engagementLevelConfig=null;try{engagementLevelConfig=JSON.parse(currentUrlConfigOnScroll.engagementLevelConfig);}catch(ex){}
ENGAGEMENT_ON_SCROLL_PERCENTAGE=engagementLevelConfig.triggerScrollPercent;pixel.ON_SCROLL_INTERVAL_IN_MINUTES=engagementLevelConfig.intervalInMinutes;pixel.ON_SCROLL_POPUP_LIMIT_PER_DAY=engagementLevelConfig.dailyLimit;pixel.createPopup(currentUrlConfigOnScroll,"modalOnScroll");window.onscroll=function(){var scrollPercentage=pixel.getScrollPercentage();if(scrollPercentage>ENGAGEMENT_ON_SCROLL_PERCENTAGE&&pixel.shouldShowPopup("ON_SCROLL")){pixel.onsiteCurrentUrlNotificationConfig["ON_SCROLL"]=currentUrlConfigOnScroll;pixel.enableCurrentPopup("modalOnScroll",currentUrlConfigOnScroll.banner);pixel.updateLastShown("ON_SCROLL");}};}
if(currentUrlConfigOnIdleTime){var engagementLevelConfigOnIdleTime=null;try{engagementLevelConfigOnIdleTime=JSON.parse(currentUrlConfigOnIdleTime.engagementLevelConfig);}catch(ex){}
pixel.ON_IDLE_TIME_INTERVAL_IN_MINUTES=engagementLevelConfigOnIdleTime.intervalInMinutes;pixel.ON_IDLE_TIME_POPUP_LIMIT_PER_DAY=engagementLevelConfigOnIdleTime.dailyLimit;pixel.IDLE_TIME_IN_MINUTES=engagementLevelConfigOnIdleTime.idleTimeInMinutes;pixel.createPopup(currentUrlConfigOnIdleTime,"modalOnIdleTime");pixel.onsiteCurrentUrlNotificationConfig["ON_IDLE_TIME"]=currentUrlConfigOnIdleTime;window.addEventListener("load",pixel.resetTimer,true);var events=["mousedown","mousemove","keypress","scroll","touchstart",];events.forEach(function(name){document.addEventListener(name,pixel.resetTimer,true);});}
if(currentUrlConfigExitIntent){var engagementLevelConfig=null;try{engagementLevelConfig=JSON.parse(currentUrlConfigExitIntent.engagementLevelConfig);}catch(ex){}
pixel.EXIT_INTENT_INTERVAL_IN_MINUTES=engagementLevelConfig.intervalInMinutes;pixel.EXIT_INTENT_POPUP_LIMIT_PER_DAY=engagementLevelConfig.dailyLimit;pixel.createPopup(currentUrlConfigExitIntent,"modalExitIntent");window.addEventListener("mouseout",(e)=>{if(!e.toElement&&!e.relatedTarget){if(pixel.shouldShowPopup("EXIT_INTENT")){pixel.onsiteCurrentUrlNotificationConfig["EXIT_INTENT"]=currentUrlConfigExitIntent;pixel.enableCurrentPopup("modalExitIntent",currentUrlConfigExitIntent.banner);pixel.updateLastShown("EXIT_INTENT");}}},true);}}catch(error){}},parse:function(){try{if(!(pixel.pixelFireStatus||pixel.checkReadyStateOnIntervals)){pixel.checkReadyStateOnIntervals=setInterval(function(){if(!pixel.pixelFireStatus){pixel.checkIfPageLoadComplete();if(pixel.pageLoadStatusFlag){try{var curCamp=pixel.detectCampaign();pixel.initialize(curCamp);if(typeof pixel.getExtraParams!="undefined")
pixel.getExtraParams();pixel.getParams();pixel.finalize(curCamp);pixel.removeDuplicatePids();pixel.fireAnalyze(pixel.getQueryString(pixel.paramArray));if(!pixel.getCookie(pixel.CHATBOT_USER_COOKIE_KEY)){pixel.CHATBOT_USER_COOKIE_VALUE=pixel.getQueryStrings(pixel.CHATBOT_USER_COOKIE_KEY);if(pixel.CHATBOT_USER_COOKIE_VALUE!=null){vizLayer.phone_number=pixel.CHATBOT_USER_COOKIE_VALUE;vizLayer.WA_CONSENT="true";pixel.checkCookie(pixel.CHATBOT_USER_COOKIE_KEY,pixel.CHATBOT_USER_COOKIE_VALUE,pixel.CHATBOT_USER_COOKIE_EXPIRY);}else{return;}}
pixel.CHATBOT_USER_COOKIE_VALUE=pixel.getCookie(pixel.CHATBOT_USER_COOKIE_KEY);if(pixel.CHATBOT_USER_COOKIE_VALUE){pixel.checkReadyStateOnIntervals=0;pixel.pixelFireStatus=false;var curCamp=pixel.detectAppCampaign();pixel.initialize(curCamp);if(typeof pixel.getExtraParams!="undefined")
pixel.getExtraParams();pixel.getParams();pixel.finalize(curCamp);pixel.removeDuplicatePids();pixel.fireAnalyze(pixel.getQueryString(pixel.paramArray));}}catch(error){pixel.paramArray["param"]="999";pixel.paramArray["err"]=error;pixel.fireAnalyze(pixel.getQueryString(pixel.paramArray));}}}},500,"Javascript");}}catch(error){pixel.paramArray["param"]="999";pixel.paramArray["err"]=error;pixel.fireAnalyze(pixel.getQueryString(pixel.paramArray));}},removeDuplicatePids:function(){var pid1="",pid2="",pid3="";var segment=pixel.paramArray["param"].split("_")[0];try{if(segment&&segment=="e400"){pid1=pixel.paramArray["pid1"];pid2=pixel.paramArray["pid2"];pid3=pixel.paramArray["pid3"];if(pid1&&pid2&&pid1==pid2){pixel.deleteParam("2");}
if(pid2&&pid3&&pid2==pid3){pixel.deleteParam("3");}
if(pid1&&pid3&&pid1==pid3){pixel.deleteParam("3");}}}catch(error){}},deleteParam:function(index){try{delete pixel.paramArray["pid"+index];delete pixel.paramArray["catid"+index];delete pixel.paramArray["price"+index];delete pixel.paramArray["quantity"+index];}catch(error){}},checkIfPageLoadComplete:function(){if(document.readyState==="interactive"||document.readyState==="complete"){pixel.pageLoadStatusFlag=true;clearInterval(pixel.checkReadyStateOnIntervals);}else{pixel.pageLoadStatusFlag=false;}},getParams:function(){var option="",argFirst="",argSecond="",argThird="";var argFourth="",argFive="",argSix="",argSeven="",paramA="";for(var param in pixel.pixelConfig){paramA=param.split("_Z")[0];if(pixel.paramArray[paramA])continue;if(pixel.pixelConfig.hasOwnProperty(param)&&pixel.pixelConfig[param]){option=pixel.pixelConfig[param][1];argFirst=pixel.pixelConfig[param][0];argSecond=pixel.pixelConfig[param][2];argThird=pixel.pixelConfig[param][3];if(option){if(option==="xpath"&&argFirst&&typeof pixel.getDataFromXPath!="undefined"){pixel.paramArray[paramA]=pixel.getDataFromXPath(argFirst,argSecond);}else if(option==="url"&&argFirst&&argThird){if(argThird=="regex"&&typeof pixel.getDataFromUrl!="undefined"){pixel.paramArray[paramA]=pixel.getDataFromUrl(argFirst,argSecond);}else if(argThird=="qstring"&&typeof pixel.getParamFromUrl!="undefined"){pixel.paramArray[paramA]=pixel.getParamFromUrl(document.URL,argFirst);}}else if(option=="jsvariable"&&argFirst&&typeof pixel.getDataFromJSVar!="undefined"){pixel.paramArray[paramA]=pixel.getDataFromJSVar(argFirst);}else if(option=="udf"&&argFirst&&typeof pixel.getDataFromUDF!="undefined"){pixel.paramArray[paramA]=pixel.getDataFromUDF(argFirst,argSecond);}else if(option=="csspath"&&argFirst&&typeof pixel.getDataFromCSSPath!="undefined"){pixel.paramArray[paramA]=pixel.getDataFromCSSPath(argFirst,argSecond);}else if(option=="classname"&&argFirst&&typeof pixel.getElementsByClass!="undefined"){pixel.paramArray[paramA]=pixel.getElementsByClass(argFirst.split(",")[0],argFirst.split(",")[1],argFirst.split(",")[2]);}
argFourth=pixel.pixelConfig[param][4];argFive=pixel.pixelConfig[param][5];argSix=pixel.pixelConfig[param][6];if(argSix&&typeof pixel.getNumericField!="undefined"){pixel.paramArray[paramA]=pixel.getNumericField(pixel.paramArray[paramA],argSix);}
argSeven=pixel.pixelConfig[param][7];if(argFourth&&pixel.paramArray[paramA]){pixel.paramArray[paramA]=pixel.getSubstring(pixel.paramArray[paramA],argFourth,argFive);}
if(argSeven&&argSeven.toLowerCase()=="md5"&&typeof pixel.getMd5!="undefined"){pixel.paramArray[paramA]=pixel.getMd5(pixel.paramArray[paramA]);}
if(argSeven&&argSeven.toLowerCase()=="sha256"&&typeof pixel.getSHA256!="undefined"){pixel.paramArray[paramA]=pixel.getSHA256(pixel.paramArray[paramA]);}}}}},getSubstring:function(param,regexString,flag){var match=null;var ret="";var index=1;var regex;try{if(flag){regex=new RegExp(regexString,flag);}else{regex=new RegExp(regexString);}
match=param.toString().match(regex);if(match&&match[index]){return match[index];}}catch(error){ret="";}
return ret;},getSegParams:function(){var option="",argFirst="",argSecond="",argThird="",url=document.URL;var argFourth="",argFive="",argSix="",argSeven="",isMd5="",paramA="";for(var stage in pixel.segmentConfig){if(pixel.segmentConfig.hasOwnProperty(stage)){pixel.segParams[stage]=[];for(var param in pixel.segmentConfig[stage]){paramA=param.split("_Z")[0];if(pixel.segParams[stage][paramA])continue;if(pixel.segmentConfig[stage].hasOwnProperty(param)&&pixel.segmentConfig[stage][param]){option=pixel.segmentConfig[stage][param][1];argFirst=pixel.segmentConfig[stage][param][0];argSecond=pixel.segmentConfig[stage][param][2];argThird=pixel.segmentConfig[stage][param][3];if(option){if(option==="xpath"&&argFirst&&typeof pixel.getDataFromXPath!="undefined"){pixel.segParams[stage][paramA]=pixel.getDataFromXPath(argFirst,argSecond);}else if(option==="url"&&argFirst&&argThird){if(argThird=="regex"&&typeof pixel.getDataFromUrl!="undefined"){pixel.segParams[stage][paramA]=pixel.getDataFromUrl(argFirst,argSecond);}else if(argThird=="qstring"&&typeof pixel.getParamFromUrl!="undefined"){pixel.segParams[stage][paramA]=pixel.getParamFromUrl(url,argFirst);}}else if(option=="jsvariable"&&argFirst&&typeof pixel.getDataFromJSVar!="undefined"){pixel.segParams[stage][paramA]=pixel.getDataFromJSVar(argFirst);}else if(option=="csspath"&&argFirst&&typeof pixel.getDataFromCSSPath!="undefined"){pixel.segParams[stage][paramA]=pixel.getDataFromCSSPath(argFirst,argSecond);}else if(option=="udf"&&argFirst&&typeof pixel.getDataFromUDF!="undefined"){pixel.segParams[stage][paramA]=pixel.getDataFromUDF(argFirst,argSecond);}else if(option=="classname"&&argFirst&&typeof pixel.getElementsByClass!="undefined"){pixel.segParams[stage][paramA]=pixel.getElementsByClass(argFirst.split(",")[0],argFirst.split(",")[1],argFirst.split(",")[2]);}
argFourth=pixel.segmentConfig[stage][param][4];argFive=pixel.segmentConfig[stage][param][5];argSix=pixel.segmentConfig[stage][param][6];if(argSix&&typeof pixel.getNumericField!="undefined"){pixel.segParams[stage][paramA]=pixel.getNumericField(pixel.segParams[stage][paramA],argSix);}
argSeven=pixel.segmentConfig[stage][param][7];isMd5=argSeven&&argSeven.toLowerCase()=="md5";if(argFourth&&pixel.segParams[stage][paramA]){pixel.segParams[stage][paramA]=pixel.getSubstring(pixel.segParams[stage][paramA],argFourth,argFive);}}}}
pixel.segParams[stage]["URL"]=url;}}},getCookie:function(cookieId){var cookies=document.cookie;if(!cookieId){return"";}
var cookieArray=cookies.split(";");for(var key in cookieArray){if(cookieArray.hasOwnProperty(key)){var matchArray=cookieArray[key].match(/\s*(.*)=(.*)/);if(matchArray){if(matchArray[1]===cookieId&&matchArray[2]){return matchArray[2];}}}}
return"";},getMd5:function(str){if(str&&str!==""){var xl;var rotateLeft=function(lValue,iShiftBits){return(lValue<<iShiftBits)|(lValue>>>(32-iShiftBits));};var addUnsigned=function(lX,lY){var lX4,lY4,lX8,lY8,lResult;lX8=lX&0x80000000;lY8=lY&0x80000000;lX4=lX&0x40000000;lY4=lY&0x40000000;lResult=(lX&0x3fffffff)+(lY&0x3fffffff);if(lX4&lY4){return lResult^0x80000000^lX8^lY8;}
if(lX4|lY4){if(lResult&0x40000000){return lResult^0xc0000000^lX8^lY8;}else{return lResult^0x40000000^lX8^lY8;}}else{return lResult^lX8^lY8;}};var _F=function(x,y,z){return(x&y)|(~x&z);};var _G=function(x,y,z){return(x&z)|(y&~z);};var _H=function(x,y,z){return x^y^z;};var _I=function(x,y,z){return y^(x|~z);};var _FF=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_F(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _GG=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_G(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _HH=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_H(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _II=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_I(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var convertToWordArray=function(str){var lWordCount;var lMessageLength=str.length;var lNumberOfWords_temp1=lMessageLength+8;var lNumberOfWords_temp2=(lNumberOfWords_temp1-(lNumberOfWords_temp1%64))/64;var lNumberOfWords=(lNumberOfWords_temp2+1)*16;var lWordArray=new Array(lNumberOfWords-1);var lBytePosition=0;var lByteCount=0;while(lByteCount<lMessageLength){lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=lWordArray[lWordCount]|(str.charCodeAt(lByteCount)<<lBytePosition);lByteCount++;}
lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=lWordArray[lWordCount]|(0x80<<lBytePosition);lWordArray[lNumberOfWords-2]=lMessageLength<<3;lWordArray[lNumberOfWords-1]=lMessageLength>>>29;return lWordArray;};var wordToHex=function(lValue){var wordToHexValue="",wordToHexValue_temp="",lByte,lCount;for(lCount=0;lCount<=3;lCount++){lByte=(lValue>>>(lCount*8))&255;wordToHexValue_temp="0"+lByte.toString(16);wordToHexValue=wordToHexValue+
wordToHexValue_temp.substr(wordToHexValue_temp.length-2,2);}
return wordToHexValue;};var utf8_encode=function(argString){if(argString===null||typeof argString==="undefined"){return"";}
var string=argString+"";var utftext="",end,start;start=end=0;var stringl=string.length;for(var n=0;n<stringl;n++){var c1=string.charCodeAt(n);var enc=null;if(c1<128){end++;}else if(c1>127&&c1<2048){enc=String.fromCharCode((c1>>6)|192,(c1&63)|128);}else if((c1&0xf800)!=0xd800){enc=String.fromCharCode((c1>>12)|224,((c1>>6)&63)|128,(c1&63)|128);}else{if((c1&0xfc00)!=0xd800){throw new RangeError("Unmatched trail surrogate at "+n);}
var c2=string.charCodeAt(++n);if((c2&0xfc00)!=0xdc00){throw new RangeError("Unmatched lead surrogate at "+(n-1));}
c1=((c1&0x3ff)<<10)+(c2&0x3ff)+0x10000;enc=String.fromCharCode((c1>>18)|240,((c1>>12)&63)|128,((c1>>6)&63)|128,(c1&63)|128);}
if(enc!==null){if(end>start){utftext+=string.slice(start,end);}
utftext+=enc;start=end=n+1;}}
if(end>start){utftext+=string.slice(start,stringl);}
return utftext;};var x=[],k,AA,BB,CC,DD,a,b,c,d,S11=7,S12=12,S13=17,S14=22,S21=5,S22=9,S23=14,S24=20,S31=4,S32=11,S33=16,S34=23,S41=6,S42=10,S43=15,S44=21;str=utf8_encode(str);x=convertToWordArray(str);a=0x67452301;b=0xefcdab89;c=0x98badcfe;d=0x10325476;xl=x.length;for(k=0;k<xl;k+=16){AA=a;BB=b;CC=c;DD=d;a=_FF(a,b,c,d,x[k+0],S11,0xd76aa478);d=_FF(d,a,b,c,x[k+1],S12,0xe8c7b756);c=_FF(c,d,a,b,x[k+2],S13,0x242070db);b=_FF(b,c,d,a,x[k+3],S14,0xc1bdceee);a=_FF(a,b,c,d,x[k+4],S11,0xf57c0faf);d=_FF(d,a,b,c,x[k+5],S12,0x4787c62a);c=_FF(c,d,a,b,x[k+6],S13,0xa8304613);b=_FF(b,c,d,a,x[k+7],S14,0xfd469501);a=_FF(a,b,c,d,x[k+8],S11,0x698098d8);d=_FF(d,a,b,c,x[k+9],S12,0x8b44f7af);c=_FF(c,d,a,b,x[k+10],S13,0xffff5bb1);b=_FF(b,c,d,a,x[k+11],S14,0x895cd7be);a=_FF(a,b,c,d,x[k+12],S11,0x6b901122);d=_FF(d,a,b,c,x[k+13],S12,0xfd987193);c=_FF(c,d,a,b,x[k+14],S13,0xa679438e);b=_FF(b,c,d,a,x[k+15],S14,0x49b40821);a=_GG(a,b,c,d,x[k+1],S21,0xf61e2562);d=_GG(d,a,b,c,x[k+6],S22,0xc040b340);c=_GG(c,d,a,b,x[k+11],S23,0x265e5a51);b=_GG(b,c,d,a,x[k+0],S24,0xe9b6c7aa);a=_GG(a,b,c,d,x[k+5],S21,0xd62f105d);d=_GG(d,a,b,c,x[k+10],S22,0x2441453);c=_GG(c,d,a,b,x[k+15],S23,0xd8a1e681);b=_GG(b,c,d,a,x[k+4],S24,0xe7d3fbc8);a=_GG(a,b,c,d,x[k+9],S21,0x21e1cde6);d=_GG(d,a,b,c,x[k+14],S22,0xc33707d6);c=_GG(c,d,a,b,x[k+3],S23,0xf4d50d87);b=_GG(b,c,d,a,x[k+8],S24,0x455a14ed);a=_GG(a,b,c,d,x[k+13],S21,0xa9e3e905);d=_GG(d,a,b,c,x[k+2],S22,0xfcefa3f8);c=_GG(c,d,a,b,x[k+7],S23,0x676f02d9);b=_GG(b,c,d,a,x[k+12],S24,0x8d2a4c8a);a=_HH(a,b,c,d,x[k+5],S31,0xfffa3942);d=_HH(d,a,b,c,x[k+8],S32,0x8771f681);c=_HH(c,d,a,b,x[k+11],S33,0x6d9d6122);b=_HH(b,c,d,a,x[k+14],S34,0xfde5380c);a=_HH(a,b,c,d,x[k+1],S31,0xa4beea44);d=_HH(d,a,b,c,x[k+4],S32,0x4bdecfa9);c=_HH(c,d,a,b,x[k+7],S33,0xf6bb4b60);b=_HH(b,c,d,a,x[k+10],S34,0xbebfbc70);a=_HH(a,b,c,d,x[k+13],S31,0x289b7ec6);d=_HH(d,a,b,c,x[k+0],S32,0xeaa127fa);c=_HH(c,d,a,b,x[k+3],S33,0xd4ef3085);b=_HH(b,c,d,a,x[k+6],S34,0x4881d05);a=_HH(a,b,c,d,x[k+9],S31,0xd9d4d039);d=_HH(d,a,b,c,x[k+12],S32,0xe6db99e5);c=_HH(c,d,a,b,x[k+15],S33,0x1fa27cf8);b=_HH(b,c,d,a,x[k+2],S34,0xc4ac5665);a=_II(a,b,c,d,x[k+0],S41,0xf4292244);d=_II(d,a,b,c,x[k+7],S42,0x432aff97);c=_II(c,d,a,b,x[k+14],S43,0xab9423a7);b=_II(b,c,d,a,x[k+5],S44,0xfc93a039);a=_II(a,b,c,d,x[k+12],S41,0x655b59c3);d=_II(d,a,b,c,x[k+3],S42,0x8f0ccc92);c=_II(c,d,a,b,x[k+10],S43,0xffeff47d);b=_II(b,c,d,a,x[k+1],S44,0x85845dd1);a=_II(a,b,c,d,x[k+8],S41,0x6fa87e4f);d=_II(d,a,b,c,x[k+15],S42,0xfe2ce6e0);c=_II(c,d,a,b,x[k+6],S43,0xa3014314);b=_II(b,c,d,a,x[k+13],S44,0x4e0811a1);a=_II(a,b,c,d,x[k+4],S41,0xf7537e82);d=_II(d,a,b,c,x[k+11],S42,0xbd3af235);c=_II(c,d,a,b,x[k+2],S43,0x2ad7d2bb);b=_II(b,c,d,a,x[k+9],S44,0xeb86d391);a=addUnsigned(a,AA);b=addUnsigned(b,BB);c=addUnsigned(c,CC);d=addUnsigned(d,DD);}
var temp=wordToHex(a)+wordToHex(b)+wordToHex(c)+wordToHex(d);return temp.toLowerCase();}
return"";},removeJunk:function(str){if(str){str=str.toString();str=str.replace(/\&lt\;/g,"<").replace(/\&gt\;/g,">").replace(/\&quot\;/g,'"').replace(/\&amp\;/g,"&").replace(/\&nbsp\;/g," ");str=str.replace(/(<([^>]+)>)/gi,"").replace(/[ \t\r\n]+/g," ").replace(/^\s+|\s+$/g,"");return str;}
return"";},getQueryString:function(paramArray){var account_id=paramArray["account_id"];var queryString="?account_id="+account_id;delete paramArray["account_id"];var value="";for(var key in paramArray){if(paramArray.hasOwnProperty(key)){value=paramArray[key];if(key=="param")value=paramArray[key].split("_")[0];queryString+="&"+key+"="+this.encodeParam(value);}}
return queryString;},selectTrafficSource:function(referrer){if(referrer){if(/https?:\/\/[^\/]*\.google\.[^\/]*/i.test(referrer)){if(/[^a-z]gclid[^a-z0-9]/i.test(referrer)){return"SEM";}else{return"SEO";}}else if(/https?:\/\/[^\/]*\.linkedin\.[^\/]*/i.test(referrer)){return"linkedin";}else if(/https?:\/\/t\.co/i.test(referrer)){return"twitter";}}else{return"";}},selectDomain:function(){if(pixel.cookieDomain&&~document.domain.indexOf(pixel.cookieDomain)&&document.domain.indexOf(pixel.cookieDomain)+
pixel.cookieDomain.length===document.domain.length){return 1;}else{var listOfDomains=pixel.domainList;for(var i=1;i<listOfDomains.length;i++){if(document.domain.indexOf(listOfDomains[i])+
listOfDomains[i].length===document.domain.length){pixel.cookieDomain=listOfDomains[i];return 0;}}}
pixel.cookieDomain=document.domain;return-1;},contains:function(text,key){if(!(text&&key)){return false;}
return text.indexOf(key)>-1;},getDataFromJSVar:function(var_name){var var_name_array=var_name.split(".");var length=var_name_array.length;var splitArray=null;var match=null;var arr_regex=/[\['"]?((\w|-|\s)+)['"\]]?/;var variable,matchArray,variable_value;try{variable=var_name_array[0];if(variable.indexOf("[")>0){splitArray=variable.split("[");variable_value=window[splitArray[0]];for(var i=1;i<splitArray.length;i++){match=splitArray[i].match(arr_regex);variable_value=variable_value[match[1]];}}else variable_value=window[variable];}catch(error){return"";}
var ret=variable_value;try{for(var i=1;i<length;i++){variable=var_name_array[i];if(variable.indexOf("[")>0){splitArray=variable.split("[");variable_value=variable_value[splitArray[0]];for(var j=1;j<splitArray.length;j++){match=splitArray[j].match(arr_regex);variable_value=variable_value[match[1]];}}else{variable_value=variable_value[variable];}}
ret=variable_value;}catch(error){return"";}
return typeof ret=="undefined"?"":ret;},};pixel.encodeParam=function(parameter){if(parameter){parameter=pixel.removeJunk(parameter);parameter=encodeURIComponent(parameter);return parameter;}
return"";};pixel.fireAnalyze=function(srcURL){var baseUrl=("https:"==document.location.protocol?"https://sg-pl":"http://sg-pl")+".vizury.com/analyze/analyze.php";var domain=pixel.cookieDomain;var fpcUrl=("https:"==document.location.protocol?"https://sg-pl":"http://sg-pl")+".vizury.com/analyze/cookieCallback.php?cb="+
domain;clearInterval(pixel.checkReadyStateOnIntervals);if(!pixel.pixelFireStatus){var iframeElement=document.createElement("iframe");var vizCookie=pixel.vizidCookie("_vz",domain);iframeElement.src=baseUrl+
srcURL+"&cb="+
vizCookie+
(pixel.isSafari()?"&csm=2":"");iframeElement.scrolling="no";iframeElement.width=1;iframeElement.height=1;iframeElement.marginheight=0;iframeElement.marginwidth=0;iframeElement.frameborder=0;iframeElement.style.display="none";pixel.pixelFireStatus=true;var node=document.getElementsByTagName("script")[0];node.parentNode.insertBefore(iframeElement,node);if(iframeElement.attachEvent){iframeElement.attachEvent("onload",pixel.callBackViz(fpcUrl));}else{iframeElement.onload=pixel.callBackViz(fpcUrl);}}};pixel.detectCampaign=function(){var curCamp="VIZVRM7929";var url=document.URL;if(true){curCamp="VIZVRM7929";}
return curCamp;};pixel.detectAppCampaign=function(){var curCamp="VIZVRM7935";var url=document.URL;if(true){curCamp="VIZVRM7935";}
return curCamp;};pixel.initialize=function(curCamp){var url=document.URL;var refurl=document.referrer;pixel.paramArray["URL"]=url;pixel.paramArray["referrer"]=refurl?refurl:"";pixel.paramArray["ts"]=pixel.selectTrafficSource(refurl);pixel.paramArray["fp34"]=pixel.getMd5(pixel.getCookie("_ga"));pixel.paramArray["account_id"]=curCamp;if(curCamp=="VIZVRM7935"){pixel.paramArray["account_id"]="VIZARD";}
pixel.paramArray["param"]="e000";pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;pixel.segmentConfig={e400:{pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],},e400_1:{pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],},e200:{pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],},e100:{pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],},};pixel.getSegParams();pixel.extraParams=[];pixel.cookieDomain="www.zoomcar.com";pixel.domainList=["www.zoomcar.com"];if(pixel.selectDomain)pixel.selectDomain();pixel.clickTrackers="";var config_e400={pid1:["vizLayer.pid1","jsvariable","","","(.*)","","",""],price1:["vizLayer.price1","jsvariable","","","(.*)","","",""],cartval:["vizLayer.cartval","jsvariable","","","(.*)","","",""],pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],};var config_e400_1={pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],};var config_e200={catid:["vizLayer.catid1","jsvariable","","","(.*)","","",""],pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],};var config_e100={pagetype:["vizLayer.type","jsvariable","","","(.*)","","",""],};if(pixel.segParams["e400"]["subcat1id"]!=undefined&&pixel.segParams["e400"]["subcat1id"]!=""&&pixel.segParams["e400"]["catid"]!=undefined&&pixel.segParams["e400"]["catid"]!="")
pixel.segParams["e400"]["subcat1id"]=pixel.segParams["e400"]["catid"]+"_"+
pixel.segParams["e400"]["subcat1id"];if(pixel.segParams["e400"]["subcat2id"]!=undefined&&pixel.segParams["e400"]["subcat2id"]!=""&&pixel.segParams["e400"]["catid"]!=undefined&&pixel.segParams["e400"]["catid"]!=""&&pixel.segParams["e400"]["subcat1id"]!=undefined&&pixel.segParams["e400"]["subcat1id"]!="")
pixel.segParams["e400"]["subcat2id"]=pixel.segParams["e400"]["subcat1id"]+"_"+
pixel.segParams["e400"]["subcat2id"];if(pixel.segParams["e400_1"]["subcat1id"]!=undefined&&pixel.segParams["e400_1"]["subcat1id"]!=""&&pixel.segParams["e400_1"]["catid"]!=undefined&&pixel.segParams["e400_1"]["catid"]!="")
pixel.segParams["e400_1"]["subcat1id"]=pixel.segParams["e400_1"]["catid"]+"_"+
pixel.segParams["e400_1"]["subcat1id"];if(pixel.segParams["e400_1"]["subcat2id"]!=undefined&&pixel.segParams["e400_1"]["subcat2id"]!=""&&pixel.segParams["e400_1"]["catid"]!=undefined&&pixel.segParams["e400_1"]["catid"]!=""&&pixel.segParams["e400_1"]["subcat1id"]!=undefined&&pixel.segParams["e400_1"]["subcat1id"]!="")
pixel.segParams["e400_1"]["subcat2id"]=pixel.segParams["e400_1"]["subcat1id"]+"_"+
pixel.segParams["e400_1"]["subcat2id"];if(pixel.segParams["e200"]["subcat1id"]!=undefined&&pixel.segParams["e200"]["subcat1id"]!=""&&pixel.segParams["e200"]["catid"]!=undefined&&pixel.segParams["e200"]["catid"]!="")
pixel.segParams["e200"]["subcat1id"]=pixel.segParams["e200"]["catid"]+"_"+
pixel.segParams["e200"]["subcat1id"];if(pixel.segParams["e200"]["subcat2id"]!=undefined&&pixel.segParams["e200"]["subcat2id"]!=""&&pixel.segParams["e200"]["catid"]!=undefined&&pixel.segParams["e200"]["catid"]!=""&&pixel.segParams["e200"]["subcat1id"]!=undefined&&pixel.segParams["e200"]["subcat1id"]!="")
pixel.segParams["e200"]["subcat2id"]=pixel.segParams["e200"]["subcat1id"]+"_"+
pixel.segParams["e200"]["subcat2id"];if(pixel.segParams["e100"]["subcat1id"]!=undefined&&pixel.segParams["e100"]["subcat1id"]!=""&&pixel.segParams["e100"]["catid"]!=undefined&&pixel.segParams["e100"]["catid"]!="")
pixel.segParams["e100"]["subcat1id"]=pixel.segParams["e100"]["catid"]+"_"+
pixel.segParams["e100"]["subcat1id"];if(pixel.segParams["e100"]["subcat2id"]!=undefined&&pixel.segParams["e100"]["subcat2id"]!=""&&pixel.segParams["e100"]["catid"]!=undefined&&pixel.segParams["e100"]["catid"]!=""&&pixel.segParams["e100"]["subcat1id"]!=undefined&&pixel.segParams["e100"]["subcat1id"]!="")
pixel.segParams["e100"]["subcat2id"]=pixel.segParams["e100"]["subcat1id"]+"_"+
pixel.segParams["e100"]["subcat2id"];if(pixel.contains(pixel.segParams["e400_1"]["pagetype"],"payment_page")){pixel.pixelConfig=config_e400_1;pixel.paramArray["param"]="e400_1";}else if(pixel.contains(pixel.segParams["e400"]["pagetype"],"shopping_cart")){pixel.pixelConfig=config_e400;pixel.paramArray["param"]="e400";}else if(pixel.contains(pixel.segParams["e200"]["pagetype"],"search_page")){pixel.pixelConfig=config_e200;pixel.paramArray["param"]="e200";}else if(pixel.contains(pixel.segParams["e100"]["pagetype"],"home_page")){pixel.pixelConfig=config_e100;pixel.paramArray["param"]="e100";}};pixel.callBackViz=function(url){url=pixel.isSafari()?url+"&sf=y":url;var pTag=document.getElementsByTagName("script")[0];var scb=document.createElement("script");scb.type="text/javascript";scb.src=url;scb.async=true;pTag.parentNode.insertBefore(scb,pTag);};pixel.vizidCookie=function(ckName,valid_domain){var vizIdCookieData=pixel.getCookie(ckName);if(!vizIdCookieData){vizIdCookieData=pixel.generateVizCookie();pixel.setCookie(ckName,vizIdCookieData,365,valid_domain);}
return vizIdCookieData;};pixel.generateVizCookie=function(){var prefix=pixel.isSafari()?"vizSF_":"viz_";var seed=0x71314a;var time=parseInt(new Date().getTime()/1000,10).toString(16);var random=Math.floor(Math.random()*seed).toString(16);while(random.length<5){random=random+Math.floor(Math.random()*seed).toString(16);}
random=random.slice(random.length-5);var cookie=prefix+time+random;return cookie;};pixel.setCookie=function(c_name,value,exdays,valid_domain){var domain_string=valid_domain?"; domain="+valid_domain:"";if(exdays>0){var exdate=new Date();exdate.setDate(exdate.getDate()+exdays);var c_value=encodeURIComponent(value)+
(exdays==null?"":"; expires="+exdate.toUTCString())+"; path=/"+
domain_string;document.cookie=c_name+"="+c_value;}else{document.cookie=c_name+"="+encodeURIComponent(value);}};pixel.isSafari=function(){return(Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor")>0||(function(p){return p.toString()==="[object SafariRemoteNotification]";})(!window["safari"]||safari.pushNotification));};pixel.finalize=function(curCamp){if(curCamp=="VIZVRM7929"){if(pixel.paramArray["subcat1id"]!=undefined&&pixel.paramArray["subcat1id"]!=""&&pixel.paramArray["catid"]!=undefined&&pixel.paramArray["catid"]!="")
pixel.paramArray["subcat1id"]=pixel.paramArray["catid"]+"_"+pixel.paramArray["subcat1id"];if(pixel.paramArray["subcat2id"]!=undefined&&pixel.paramArray["subcat2id"]!=""&&pixel.paramArray["catid"]!=undefined&&pixel.paramArray["catid"]!=""&&pixel.paramArray["subcat1id"]!=undefined&&pixel.paramArray["subcat1id"]!="")
pixel.paramArray["subcat2id"]=pixel.paramArray["subcat1id"]+"_"+pixel.paramArray["subcat2id"];if(pixel.paramArray["param"]=="e400"){pixel.paramArray.pagetype=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;pixel.paramArray["ealevel"]=1;}else if(pixel.paramArray["param"]=="e400_1"){pixel.paramArray.pagetype=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=2;pixel.paramArray["ealevel"]=2;}else if(pixel.paramArray["param"]=="e200"){pixel.paramArray.pagetype=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;}else if(pixel.paramArray["param"]=="e100"){pixel.paramArray.pagetype=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;}}else{pixel.paramArray["vizard"]=1;pixel.paramArray["vizard_pt"]="event";pixel.paramArray["package_id"]="466";pixel.paramArray["adv_id"]=pixel.CHATBOT_USER_COOKIE_VALUE;pixel.paramArray["csm"]=3;pixel.paramArray["is_shoffr_analyze"]=1;pixel.paramArray["phone_number"]=vizLayer.phone_number;pixel.paramArray["WA_CONSENT"]=vizLayer.WA_CONSENT;if(pixel.paramArray["subcat1id"]!=undefined&&pixel.paramArray["subcat1id"]!=""&&pixel.paramArray["catid"]!=undefined&&pixel.paramArray["catid"]!="")
pixel.paramArray["subcat1id"]=pixel.paramArray["catid"]+"_"+pixel.paramArray["subcat1id"];if(pixel.paramArray["subcat2id"]!=undefined&&pixel.paramArray["subcat2id"]!=""&&pixel.paramArray["catid"]!=undefined&&pixel.paramArray["catid"]!=""&&pixel.paramArray["subcat1id"]!=undefined&&pixel.paramArray["subcat1id"]!="")
pixel.paramArray["subcat2id"]=pixel.paramArray["subcat1id"]+"_"+pixel.paramArray["subcat2id"];if(pixel.paramArray["param"]=="e400"){pixel.paramArray["vizard_event_name"]=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;pixel.paramArray["ealevel"]=1;}else if(pixel.paramArray["param"]=="e400_1"){pixel.paramArray["vizard_event_name"]=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;pixel.paramArray["ealevel"]=2;}else if(pixel.paramArray["param"]=="e200"){pixel.paramArray["vizard_event_name"]=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;}else if(pixel.paramArray["param"]=="e100"){pixel.paramArray["vizard_event_name"]=vizLayer.type;pixel.paramArray["section"]=1;pixel.paramArray["level"]=1;}}};pixel.getQueryStrings=function(param){var assoc={};var decode=function(s){return decodeURIComponent(s.replace(/\+/g," "));};var queryString=location.search.substring(1);var keyValues=queryString.split("&");for(var i in keyValues){var key=keyValues[i].split("=");if(key.length>1){assoc[decode(key[0])]=decode(key[1]);}}
return assoc[param];};pixel.checkCookie=function(cname,cvalue,expiry){if(cvalue!=""&&cvalue!=null){pixel.setCookie(cname,cvalue,expiry);}};pixel.setCookieData=function(cookieName,messageType){var last_shown,cd,cookie_string,cookie_expiry,shown_count=0,shown_count_on_idle_time=0;var shown_count_exit_intent=0,last_shown_exit_intent;var last_shown_on_idle_time,cookie_data;if(pixel.isCookiePresent("onSiteMsgCookie")){cookie_data=pixel.getCookieData("onSiteMsgCookie");last_shown_on_idle_time=new Date(cookie_data.last_shown_on_idle_time);last_shown_exit_intent=new Date(cookie_data.last_shown_exit_intent);last_shown=new Date(cookie_data.last_shown);shown_count=cookie_data.shown_count;shown_count_on_idle_time=cookie_data.shown_count_on_idle_time;shown_count_exit_intent=cookie_data.shown_count_exit_intent;}else{last_shown=new Date();last_shown=last_shown.toUTCString();last_shown_on_idle_time=new Date();last_shown_exit_intent=new Date();last_shown_on_idle_time=last_shown_on_idle_time.toUTCString();last_shown_exit_intent=last_shown_exit_intent.toUTCString();}
if(messageType==="ON_SCROLL"){last_shown=new Date();last_shown=last_shown.toUTCString();}else if(messageType=="ON_IDLE_TIME"){last_shown_on_idle_time=new Date();last_shown_on_idle_time=last_shown_on_idle_time.toUTCString();}else if(messageType==="EXIT_INTENT"){last_shown_exit_intent=new Date();last_shown_exit_intent=last_shown_exit_intent.toUTCString();}
cd={last_shown:last_shown,shown_count:shown_count,last_shown_on_idle_time:last_shown_on_idle_time,shown_count_on_idle_time:shown_count_on_idle_time,last_shown_exit_intent:last_shown_exit_intent,shown_count_exit_intent:shown_count_exit_intent,};cookie_expiry=new Date();cookie_expiry.setTime(cookie_expiry.getTime()+3*365*24*60*60*1000);cookie_expiry=cookie_expiry.toUTCString();cookie_string=cookieName+"="+
JSON.stringify(cd)+"; expires="+
cookie_expiry+"; path=/";document.cookie=cookie_string;};pixel.getCookieData=function(cookieName){var cookies=document.cookie;var regex=new RegExp(cookieName+"=(.[^;]*);?");if(regex.test(cookies)){return JSON.parse(cookies.match(regex)[1]);}
return JSON.parse("{}");};pixel.updateLastShown=function(messageType){if(!pixel.isCookiePresent(pixel.ONSITE_MESSAGE_COOKIE_NAME)){pixel.initializeCookie();}
var cookie_data=pixel.getCookieData(pixel.ONSITE_MESSAGE_COOKIE_NAME);var cookie_json_object=cookie_data;if(messageType==="ON_SCROLL"){var last_shown_onscroll=new Date();last_shown_onscroll=last_shown_onscroll.toUTCString();cookie_json_object.shown_count_onscroll+=1;cookie_json_object.last_shown_onscroll=last_shown_onscroll;}else if(messageType==="ON_IDLE_TIME"){last_shown_on_idle_time=new Date();last_shown_on_idle_time=last_shown_on_idle_time.toUTCString();cookie_json_object.shown_count_on_idle_time+=1;cookie_json_object.last_shown_on_idle_time=last_shown_on_idle_time;}else if(messageType==="EXIT_INTENT"){last_shown_exit_intent=new Date();last_shown_exit_intent=last_shown_exit_intent.toUTCString();cookie_json_object.shown_count_exit_intent+=1;cookie_json_object.last_shown_exit_intent=last_shown_exit_intent;}
var cookie_expiry=new Date();cookie_expiry.setTime(cookie_expiry.getTime()+3*365*24*60*60*1000);cookie_expiry=cookie_expiry.toUTCString();var cookie_string=pixel.ONSITE_MESSAGE_COOKIE_NAME+"="+
JSON.stringify(cookie_json_object)+"; expires="+
cookie_expiry+"; path=/";document.cookie=cookie_string;return;};pixel.initializeCookie=function(){var cd,cookie_string,cookie_expiry;var last_shown_on_idle_time,last_shown_onscroll,last_shown_exit_intent;last_shown_onscroll=new Date();last_shown_onscroll=last_shown_onscroll.toUTCString();last_shown_on_idle_time=new Date();last_shown_on_idle_time=last_shown_on_idle_time.toUTCString();last_shown_exit_intent=new Date();last_shown_exit_intent=last_shown_exit_intent.toUTCString();cd={last_shown_on_idle_time:last_shown_on_idle_time,shown_count_on_idle_time:0,last_shown_onscroll:last_shown_onscroll,shown_count_onscroll:0,last_shown_exit_intent:last_shown_exit_intent,shown_count_exit_intent:0,};cookie_expiry=new Date();cookie_expiry.setTime(cookie_expiry.getTime()+3*365*24*60*60*1000);cookie_expiry=cookie_expiry.toUTCString();cookie_string=pixel.ONSITE_MESSAGE_COOKIE_NAME+"="+
JSON.stringify(cd)+"; expires="+
cookie_expiry+"; path=/";document.cookie=cookie_string;return;};pixel.resetCookieDataForDay=function(messageType){var cookie_data=pixel.getCookieData(pixel.ONSITE_MESSAGE_COOKIE_NAME);var cookie_json_object=cookie_data;if(messageType==="ON_SCROLL"){var last_shown_onscroll=new Date();last_shown_onscroll=last_shown_onscroll.toUTCString();cookie_json_object.shown_count_onscroll=0;cookie_json_object.last_shown_onscroll=last_shown_onscroll;}else if(messageType==="ON_IDLE_TIME"){last_shown_on_idle_time=new Date();last_shown_on_idle_time=last_shown_on_idle_time.toUTCString();cookie_json_object.shown_count_on_idle_time=0;cookie_json_object.last_shown_on_idle_time=last_shown_on_idle_time;}else if(messageType==="EXIT_INTENT"){last_shown_exit_intent=new Date();last_shown_exit_intent=last_shown_exit_intent.toUTCString();cookie_json_object.shown_count_exit_intent=0;cookie_json_object.last_shown_exit_intent=last_shown_exit_intent;}
var cookie_expiry=new Date();cookie_expiry.setTime(cookie_expiry.getTime()+3*365*24*60*60*1000);cookie_expiry=cookie_expiry.toUTCString();var cookie_string=pixel.ONSITE_MESSAGE_COOKIE_NAME+"="+
JSON.stringify(cookie_json_object)+"; expires="+
cookie_expiry+"; path=/";document.cookie=cookie_string;return;};pixel.shouldShowPopup=function(messageType){if(pixel.currentOnsitePopup){return false;}
if(!pixel.isCookiePresent(pixel.ONSITE_MESSAGE_COOKIE_NAME)){return true;}
var last_shown_date,difference_mins,shown_count;var current_date=new Date();var cookie_data=pixel.getCookieData(pixel.ONSITE_MESSAGE_COOKIE_NAME);var cookie_json_object=cookie_data;if(messageType==="ON_SCROLL"){last_shown_date=new Date(cookie_data.last_shown_onscroll);difference_mins=pixel.getTimeDifference(last_shown_date,current_date);shown_count=cookie_json_object.shown_count_onscroll;if(difference_mins>60*24*1){pixel.resetCookieDataForDay("ON_SCROLL");return true;}
if(difference_mins>pixel.ON_SCROLL_INTERVAL_IN_MINUTES&&shown_count<pixel.ON_SCROLL_POPUP_LIMIT_PER_DAY){return true;}else{return false;}}else if(messageType=="ON_IDLE_TIME"){last_shown_date=new Date(cookie_data.last_shown_on_idle_time);difference_mins=pixel.getTimeDifference(last_shown_date,current_date);shown_count=cookie_json_object.shown_count_on_idle_time;if(difference_mins>60*24*1){pixel.resetCookieDataForDay("ON_IDLE_TIME");return true;}
if(difference_mins>pixel.ON_IDLE_TIME_INTERVAL_IN_MINUTES&&shown_count<pixel.ON_IDLE_TIME_POPUP_LIMIT_PER_DAY){return true;}else{return false;}}else if(messageType==="EXIT_INTENT"){last_shown_date=new Date(cookie_data.last_shown_exit_intent);difference_mins=pixel.getTimeDifference(last_shown_date,current_date);shown_count=cookie_json_object.shown_count_exit_intent;if(difference_mins>60*24*1){pixel.resetCookieDataForDay("EXIT_INTENT");return true;}
if(difference_mins>pixel.EXIT_INTENT_INTERVAL_IN_MINUTES&&shown_count<pixel.EXIT_INTENT_POPUP_LIMIT_PER_DAY){return true;}else{return false;}}
return false;};pixel.isCookiePresent=function(cookieName){var value="; "+document.cookie;var parts=value.split("; "+cookieName+"=");return parts.length>=2?true:false;};pixel.getTimeDifference=function(date1,date2,type){var timeDiff=date2-date1;if(type==="days"){return timeDiff/(1000*60*60*24);}else{return timeDiff/(1000*60);}};pixel.getScrollPercentage=function(){var heightOfWindow=window.innerHeight;var contentScrolled=window.pageYOffset;var bodyHeight=document.body.offsetHeight;if(bodyHeight-contentScrolled<=heightOfWindow){return 100;}else{var total=bodyHeight-heightOfWindow;var got=contentScrolled;var percent=parseInt((got/total)*100);return percent;}};var time;pixel.logout=function(){var urlIdleTimeConfig=pixel.onsiteCurrentUrlNotificationConfig["ON_IDLE_TIME"];if(!urlIdleTimeConfig)return;if(pixel.shouldShowPopup("ON_IDLE_TIME")){pixel.enableCurrentPopup("modalOnIdleTime",urlIdleTimeConfig.banner);pixel.updateLastShown("ON_IDLE_TIME");}};pixel.resetTimer=function(){clearTimeout(time);time=setTimeout(pixel.logout,pixel.IDLE_TIME_IN_MINUTES*60000);};pixel.loadDoc=function(){if(pixel.currentOnsitePopup!=null)return;var notify="https://onsite.vizury.com/analyze/getECOnsiteConfig?force_adv_id=VIZVRM7929";fetch(notify,{credentials:"include",headers:{Origin:window.location.protocol+window.location.hostname,},}).then(function(response){return response.text();}).then(function(text){window.localStorage.setItem("onsiteConfig",text);try{pixel.initializeOnsite();}catch(error){}}).catch(function(error){});};pixel.initializeOnsite=function(){var onsiteData=window.localStorage.getItem("onsiteConfig");if(onsiteData){pixel.onSiteNotificationConfig=JSON.parse(onsiteData);pixel.loadContentForOnSiteMsg2();}};pixel.resetOnsiteTimer=function(){clearTimeout(onsiteRefreshTime);onsiteRefreshTime=setTimeout(pixel.loadDoc,15*60*1000);};pixel.createPopup=function(currentUrlConfig,popupId){try{var currentTemplate=currentUrlConfig.template;var isStatic=currentUrlConfig.isStatic;var bannerId=currentUrlConfig.banner;var cookie=pixel.vizidCookie("_vz",pixel.cookieDomain);if(cookie==null){cookie=pixel.vizidCookie("_vz",pixel.cookieDomain);}
var campaignId=pixel.detectCampaign();campaignId=campaignId.replace("VIZVRM","");var engagementLevelConfig=null;try{engagementLevelConfig=JSON.parse(currentUrlConfig.engagementLevelConfig);}catch(ex){}
var currentImages=engagementLevelConfig.imageArr;var imagePopup=currentImages[0];var imagePopupUrl=engagementLevelConfig.redirectUrl;var onsitePopupStyleElem=document.createElement("style");var styleCSS=pixel.replaceAll(currentTemplate.templateStyleCSS,"modalOnsitePopup",popupId);onsitePopupStyleElem.innerHTML=styleCSS;document.head.appendChild(onsitePopupStyleElem);var onsitePopupMsgHTML=currentTemplate.templateHtml;onsitePopupMsgHTML=pixel.replaceAll(onsitePopupMsgHTML,"modalOnsitePopup",popupId);onsitePopupMsgHTML=pixel.replaceAll(onsitePopupMsgHTML,"{OnsiteImageSrc}",imagePopup);onsitePopupMsgHTML=pixel.replaceAll(onsitePopupMsgHTML,"{OnsiteImageRedirectUrl}",imagePopupUrl);var onsitePopupParentDiv=document.createElement("div");onsitePopupParentDiv.id=popupId;onsitePopupParentDiv.classList.add("onsite_wrapper");onsitePopupParentDiv.style.display="none";onsitePopupParentDiv.innerHTML=onsitePopupMsgHTML;document.body.appendChild(onsitePopupParentDiv);if(isStatic==1){document.getElementById(popupId).onclick=function(){document.getElementById(popupId).style.display="none";document.getElementById(popupId+"-modal").style.display="none";pixel.currentOnsitePopup=null;};document.getElementById(popupId+"-modal").getElementsByTagName("img")[0].onclick=function(){var vizCookie=pixel.vizidCookie("_vz",pixel.cookieDomain);pixel.notifyClicks(vizCookie,currentUrlConfig.banner,10826);if(imagePopupUrl){window.location.href=imagePopupUrl;}};}else{let countries=[];countries=pixel.countryListJson.COUNTRIES;let mobile_no_div=document.getElementById("mobile_number_form"+"-"+popupId);if(mobile_no_div){let selectList=document.createElement("select");selectList.setAttribute("id","countryCode"+"-"+popupId);mobile_no_div.appendChild(selectList);for(var i=0;i<countries.length;i++){var option=document.createElement("option");option.setAttribute("value",countries[i].dial_code);option.text=`${countries[i].code}(${countries[i].dial_code})`;selectList.appendChild(option);}}
document.getElementById("onsite--form"+"-"+popupId).onsubmit=(e)=>{e.preventDefault();var elements=document.getElementById("onsite--form"+"-"+popupId).elements;var obj={};for(var i=0;i<elements.length;i++){var item=elements.item(i);if(item.name=="checkbox"){if(item.checked){item.value=true;}else{item.value=false;}}
obj[item.name]=item.value;}
if(obj["mobile_no."]!=null){let countryCode=document.getElementById("countryCode"+"-"+popupId)?.value;var mobile_no=obj["mobile_no."];var isValidMobileNumber=true;try{var parsed_mobile_no=Number(mobile_no);if(isNaN(parsed_mobile_no)){isValidMobileNumber=false;}}catch(ex){isValidMobileNumber=false;}
var index=pixel.countryListJson.COUNTRIES.findIndex((a)=>a.dial_code==countryCode);if(index>-1){var countryCodeJson=pixel.countryListJson.COUNTRIES[index];var validLengthArray=countryCodeJson[countryCodeJson.name];if(mobile_no==null||!validLengthArray.includes(mobile_no.length)){isValidMobileNumber=false;}}else{isValidMobileNumber=false;}
try{if(isValidMobileNumber==false){let mobile_number_form_div=document.getElementById("mobile_number_form-"+popupId);mobile_number_form_div.childNodes[2].style.borderColor="red";mobile_number_form_div.childNodes[2].style.background="#F5C5C5";setTimeout(()=>{mobile_number_form_div.childNodes[2].style.borderColor=null;mobile_number_form_div.childNodes[2].style.background=null;},3000);return;}}catch(error){}
if(countryCode!=null&&mobile_no!=null){mobile_no=countryCode+mobile_no;}
if(mobile_no!=null&&mobile_no.length>0&&mobile_no[0]=="+"){mobile_no=mobile_no.slice(1);obj["mobile_no."]=mobile_no;}}
var onsiteData={};onsiteData["cookie"]=cookie;onsiteData["adv_id"]=campaignId;onsiteData["banner_id"]=bannerId;onsiteData["payload_json"]=obj;if(obj!=null){try{if(document.getElementById("thankyouMsg"+"-"+popupId)){document.getElementById("onsite--form"+"-"+popupId).style.display="none";document.getElementById("thankyouMsg"+"-"+popupId).style.display="flex";setTimeout(()=>{document.getElementById(popupId).style.display="none";document.getElementById(popupId+"-modal").style.display="none";document.getElementById("thankyouMsg"+"-"+popupId).style.display="none";document.getElementById("onsite--form"+"-"+popupId).style.display="";pixel.currentOnsitePopup=null;},1500);}else{document.getElementById(popupId).style.display="none";document.getElementById(popupId+"-modal").style.display="none";pixel.currentOnsitePopup=null;}
var url="https://onsitedata.vizury.com/onSiteNotifications";fetch(url,{method:"POST",body:JSON.stringify(onsiteData),headers:{"Content-type":"application/json; charset=UTF-8",},}).then((response)=>{response.json();}).catch(function(error){});}catch(e){}
try{var WA_CONSENT="true";if(obj["mobile_no."]!=null){if(obj["checkbox"]=="false"){WA_CONSENT="false";}
var pixelInterVal=setInterval(()=>{clearInterval(pixelInterVal);if(!pixel.getCookie(pixel.CHATBOT_USER_COOKIE_KEY)){pixel.CHATBOT_USER_COOKIE_VALUE=obj["mobile_no."];if(pixel.CHATBOT_USER_COOKIE_VALUE!=null){vizLayer.phone_number=pixel.CHATBOT_USER_COOKIE_VALUE;vizLayer.WA_CONSENT="true";pixel.checkCookie(pixel.CHATBOT_USER_COOKIE_KEY,pixel.CHATBOT_USER_COOKIE_VALUE,pixel.CHATBOT_USER_COOKIE_EXPIRY);}}
pixel.CHATBOT_USER_COOKIE_VALUE=pixel.getCookie(pixel.CHATBOT_USER_COOKIE_KEY);pixel.paramArray["WA_CONSENT"]=WA_CONSENT;pixel.paramArray["phone_number"]=obj["mobile_no."];pixel.paramArray["account_id"]="VIZARD";pixel.pixelFireStatus=false;pixel.paramArray["vizard"]=1;pixel.paramArray["vizard_pt"]="event";pixel.paramArray["package_id"]="466";pixel.paramArray["adv_id"]=pixel.CHATBOT_USER_COOKIE_VALUE;pixel.paramArray["csm"]=3;pixel.paramArray["is_shoffr_analyze"]=1;pixel.paramArray["vizard_event_name"]="Submit_Button_Event";pixel.fireAnalyze(pixel.getQueryString(pixel.paramArray));},500);}}catch(e){}}
for(var i=0;i<elements.length;i++){var item=elements.item(i);if(item.name=="checkbox"){item.checked=false;}
item.value="";}};document.getElementById("onsite--close"+"-"+popupId).onclick=(e)=>{e.preventDefault();document.getElementById(popupId).style.display="none";document.getElementById(popupId+"-modal").style.display="none";if(document.getElementById("thankyouMsg"+"-"+popupId)){document.getElementById("thankyouMsg"+"-"+popupId).style.display="none";}
if(document.getElementById("onsite--form"+"-"+popupId)){document.getElementById("onsite--form"+"-"+popupId).style.display="";}
pixel.currentOnsitePopup=null;var elements=document.getElementById("onsite--form"+"-"+popupId).elements;for(var i=0;i<elements.length;i++){var item=elements.item(i);if(item.name=="checkbox"){item.checked=false;}
item.value="";}};}}catch(error){}};pixel.enableCurrentPopup=function(elementId,bannerId){if(pixel.currentOnsitePopup&&document.getElementById(pixel.currentOnsitePopup)){document.getElementById(pixel.currentOnsitePopup).style.display="none";document.getElementById(pixel.currentOnsitePopup).children[1].style.display="none";pixel.currentOnsitePopup=null;}
document.getElementById(elementId).children[1].style.display="block";document.getElementById(elementId).style.display="block";pixel.currentOnsitePopup=elementId;var vizCookie=pixel.vizidCookie("_vz",pixel.cookieDomain);pixel.mobileNotify(vizCookie,bannerId,10826);};pixel.getImpressionId=function(min,max){return Math.floor(Math.random()*(max-min))+min;};pixel.mobileNotify=function(vizid,bannerId,zoneId){var iid=pixel.getImpressionId(1,999999999);var notify="https://tr.vizury.com/banners/images/common/mobile_notify.php?t=impr&u=&adid="+
bannerId+"&zid="+
zoneId+"&iid="+
iid+"&ibid=onsite&p=price&eid=_onsite";fetch(notify,{headers:{Origin:window.location.protocol+window.location.hostname,},}).then(function(response){return response.text();}).then(function(text){}).catch(function(error){});};pixel.notifyClicks=function(vizid,bannerId,zoneId){var notify="https://tr.vizury.com/vizserver//www/delivery/ck.php?ecOnsiteN=1&bannerid="+
bannerId+"&zoneid="+
zoneId+"&deviceid="+
vizid;fetch(notify,{headers:{Origin:window.location.protocol+window.location.hostname,},}).then(function(response){return response.text();}).then(function(text){}).catch(function(error){});};pixel.escapeRegExp=function(string){return string.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");};pixel.replaceAll=function(str,term,replacement){return str.replace(new RegExp(pixel.escapeRegExp(term),"g"),replacement);};if(typeof pixel!=="undefined"&&pixel&&!pixel.pixelFireStatus&&typeof pixel.parse!=="undefined"&&!(navigator.userAgent).includes("Mobile")&&!(window.location.search).includes("referrer=smartbuy")){pixel.loadDoc();window.setInterval(function(){pixel.loadDoc();},900000);pixel.parse();}
pixel.countryListJson={COUNTRIES:[{name:"India",dial_code:"+91",code:"IN",India:[10],},],};